spring.jpa.properties.hibernate.default_schema=teste_java
spring.application.name=teste_java
spring.datasource.url=jdbc:mysql://localhost:3306/teste_java
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=masterkey
spring.data.jpa.repositories.enabled=true

# Explicitly declare the dialect if auto-detection still fails
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
